In [2]:
import numpy as np
import pandas as pd
import pickle

In [4]:
df = pd.read_csv('k9_stories_500.csv')
print(f"{len(df)} rows in the data.")
df.sample(5)

72 rows in the data.

,title,mistress,synopsis
0,The Invisible Enemy,Leela,I was designed by Professor Marius for his own...
69,School Reunion,Sarah Jane,My sensors had detected a strange phenomenon. ...
11,The Underworld,Leela,Doctor Master and Mistress succeeded in locati...
67,Warrior's Gate,Romana,"Adric and I left to save Mistress Romana, but ..."
12,The Underworld,Leela,"As the R1C blasted away, loaded with the slave..."

In [12]:
#!pip install -U typing_extensions

Requirement already satisfied: typing_extensions in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (4.12.2)

In [13]:
#!pip install ollama

Requirement already satisfied: ollama in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (0.4.7)
Requirement already satisfied: httpx<0.29,>=0.27 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from ollama) (2.10.6)
Requirement already satisfied: anyio in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from httpx<0.29,>=0.27->ollama) (3.5.0)
Requirement already satisfied: certifi in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from httpx<0.29,>=0.27->ollama) (2023.7.22)
Requirement already satisfied: httpcore==1.* in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from httpx<0.29,>=0.27->ollama) (1.0.7)
Requirement already satisfied: idna in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from httpx<0.29,>=0.27->ollama) (3.4)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29,>=0.27->ollama) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from pydantic<3.0.0,>=2.9.0->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from pydantic<3.0.0,>=2.9.0->ollama) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from pydantic<3.0.0,>=2.9.0->ollama) (4.12.2)
Requirement already satisfied: sniffio>=1.1 in /Users/richardhopkins/miniconda3/lib/python3.9/site-packages (from anyio->httpx<0.29,>=0.27->ollama) (1.2.0)

In [14]:
import ollama

ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/Users/richardhopkins/miniconda3/lib/python3.9/site-packages/typing_extensions.py)

In [192]:
def get_embedding(text: str, model: str=EMBEDDING_MODEL) -> list[float]:
    result = openai.Embedding.create(
      model=model,
      input=text
    )
    return result["data"][0]["embedding"]

In [208]:
vectors = {}
for index, row in df.iterrows():
    list = get_embedding(row.synopsis)
    vectors[index]=list
    print("Vector ",index," generated")

Vector  0  generated
Vector  1  generated
Vector  2  generated
Vector  3  generated
Vector  4  generated
Vector  5  generated
Vector  6  generated
Vector  7  generated
Vector  8  generated
Vector  9  generated
Vector  10  generated
Vector  11  generated
Vector  12  generated
Vector  13  generated
Vector  14  generated
Vector  15  generated
Vector  16  generated
Vector  17  generated
Vector  18  generated
Vector  19  generated
Vector  20  generated
Vector  21  generated
Vector  22  generated
Vector  23  generated
Vector  24  generated
Vector  25  generated
Vector  26  generated
Vector  27  generated
Vector  28  generated
Vector  29  generated
Vector  30  generated
Vector  31  generated
Vector  32  generated
Vector  33  generated
Vector  34  generated
Vector  35  generated
Vector  36  generated
Vector  37  generated
Vector  38  generated
Vector  39  generated
Vector  40  generated
Vector  41  generated
Vector  42  generated
Vector  43  generated
Vector  44  generated
Vector  45  generated
Vector  46  generated
Vector  47  generated
Vector  48  generated
Vector  49  generated
Vector  50  generated
Vector  51  generated
Vector  52  generated
Vector  53  generated
Vector  54  generated
Vector  55  generated
Vector  56  generated
Vector  57  generated
Vector  58  generated
Vector  59  generated
Vector  60  generated
Vector  61  generated
Vector  62  generated
Vector  63  generated
Vector  64  generated
Vector  65  generated
Vector  66  generated
Vector  67  generated
Vector  68  generated
Vector  69  generated
Vector  70  generated
Vector  71  generated

In [224]:
len(vectors)

72

In [225]:
out=pd.DataFrame.from_dict(vectors).transpose()

In [226]:
out.tail(5)

,0,1,2,3,4,5,6,7,8,9,...,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535
67,0.012603,-0.021938,-0.004552,-0.028691,-0.013166,0.037992,-0.005749,-0.020894,-0.007057,0.001630,...,-0.015525,0.000413,0.018738,-0.012122,-0.017152,0.001869,-0.007932,-0.006647,-0.011674,0.005505
68,0.009900,-0.039846,-0.006811,-0.038067,-0.016133,0.024384,-0.005662,-0.010789,-0.016037,-0.002415,...,-0.023317,-0.013184,0.025917,-0.003934,-0.016147,0.011727,-0.011084,0.027531,-0.011939,-0.017706
69,0.002027,0.001288,-0.015131,-0.021477,-0.013615,0.016795,-0.005239,-0.019023,-0.024777,-0.025045,...,-0.001150,-0.030544,0.023395,-0.027357,-0.020109,-0.013361,-0.002045,-0.011161,-0.027498,-0.006490
70,0.016060,-0.011126,-0.010541,-0.023368,-0.016523,0.028064,-0.017040,-0.022933,-0.013528,-0.017516,...,-0.010310,-0.019530,0.021395,-0.021898,-0.022402,-0.006628,-0.013127,0.009704,-0.025900,-0.000119
71,-0.003009,-0.027943,0.000741,-0.017813,-0.024806,0.021154,-0.007933,-0.002590,-0.016109,-0.009420,...,-0.026442,-0.022669,0.025157,-0.025428,-0.020491,0.002037,-0.008981,0.002847,-0.022249,-0.000138

In [227]:
df = df.join(out)

In [228]:
df

,title,mistress,synopsis,0,1,2,3,4,5,6,...,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535
0,The Invisible Enemy,Leela,I was designed by Professor Marius for his own...,-0.001401,-0.010870,-0.009480,-0.043349,-0.004289,0.028592,-0.012089,...,-0.002584,-0.025443,0.033731,-0.023612,-0.022716,-0.006736,-0.012418,-0.023506,0.008446,-0.030674
1,The Invisible Enemy,Leela,I was put to the test when the Doctor received...,0.004073,-0.037149,-0.022510,-0.029198,-0.011665,0.033765,-0.017715,...,-0.013914,-0.023302,0.017366,-0.024592,-0.029762,-0.001318,0.008730,-0.007837,-0.013981,-0.005614
2,The Invisible Enemy,Leela,"At the medical centre, I was introduced to the...",0.004470,-0.012824,-0.003199,-0.030651,-0.014327,0.029639,-0.013945,...,0.000144,-0.029830,0.029967,-0.021368,-0.039072,-0.023542,-0.016788,0.002635,-0.012769,-0.009932
3,The Invisible Enemy,Leela,We left for Titan Base to fight off the infect...,0.010928,-0.012698,-0.022344,-0.035436,-0.002415,0.037716,-0.017026,...,-0.014639,-0.001610,0.020187,-0.024379,-0.036712,0.005210,-0.007407,0.005264,-0.002091,-0.009470
4,The Sunmakers,Leela,Doctor Master and mistress Leela were on a mis...,0.006123,-0.028114,-0.006984,-0.034806,-0.005105,0.037357,0.005023,...,-0.018418,-0.017060,0.037329,-0.029073,-0.041279,-0.012740,-0.009648,-0.006408,-0.008283,-0.009373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Warrior's Gate,Romana,"Adric and I left to save Mistress Romana, but ...",0.012603,-0.021938,-0.004552,-0.028691,-0.013166,0.037992,-0.005749,...,-0.015525,0.000413,0.018738,-0.012122,-0.017152,0.001869,-0.007932,-0.006647,-0.011674,0.005505
68,Warrior's Gate,Romana,Mistress Romana was soon freed by another Thar...,0.009900,-0.039846,-0.006811,-0.038067,-0.016133,0.024384,-0.005662,...,-0.023317,-0.013184,0.025917,-0.003934,-0.016147,0.011727,-0.011084,0.027531,-0.011939,-0.017706
69,School Reunion,Sarah Jane,My sensors had detected a strange phenomenon. ...,0.002027,0.001288,-0.015131,-0.021477,-0.013615,0.016795,-0.005239,...,-0.001150,-0.030544,0.023395,-0.027357,-0.020109,-0.013361,-0.002045,-0.011161,-0.027498,-0.006490
70,School Reunion,Sarah Jane,Doctor Master and mistress Sarah Jane confront...,0.016060,-0.011126,-0.010541,-0.023368,-0.016523,0.028064,-0.017040,...,-0.010310,-0.019530,0.021395,-0.021898,-0.022402,-0.006628,-0.013127,0.009704,-0.025900,-0.000119
71,School Reunion,Sarah Jane,Doctor Master and mistress Sarah Jane lead the...,-0.003009,-0.027943,0.000741,-0.017813,-0.024806,0.021154,-0.007933,...,-0.026442,-0.022669,0.025157,-0.025428,-0.020491,0.002037,-0.008981,0.002847,-0.022249,-0.000138

In [229]:
df.to_csv('k9_story_vectors_500.csv')